### ISSUE TITLE
WAT not showing up in IE 11 on Windows 10

### ISSUE THREAD

**Issue by Hannej** [ThePacielloGroup/WebAccessibilityToolbar#103]
I've installed the 32 and 64 bit version of WAT (WAT_2015-05-20_32.64bit.exe) on windows 10, but the toolbar will not show up in IE11.

The installation seems to have been successful, the add-on has been enabled, and Web Accessibility Toolbar is an option in the toolbar menu, but the actual toolbar still isn't visible.
When I try to toggle the view from the toolbar menu it's not turned on, I just get a popup window that lets me choose to disable the add-on.

I've tried installing and uninstalling several times, and also started IE11 as an administrator to see if I could get beyond the problem, but the toolbar still isn't viewable. 

Does anyone know how I can get it working?

**Comment by menovak** [comment]
hi Hannej

Please review Issues #96, I think some of the tactics employed there will help you get WAT running,  especially towards the end of the thread.

Thanks
Mark
