### ISSUE TITLE
No Images and Pages not loading

### ISSUE THREAD

**Issue by IkeWSC** [ThePacielloGroup/WebAccessibilityToolbar#105]
Hi all, 
I am running Windows 10 64/bit with IE 11
I DL'd and installed WAT_2015-05-20_32.64bit version
After installing and running IE I have pages, Yahoo for instance, where graphics do not load
Additionally I have pages that I go to all the time (iwon.com for one) that would not load .
Also I access a secure network via Citrix Access Gateway and now that will not load. 

Any ideas as to why I am having these issues. 

I have already uninstalled WAT and rebooted Windows to get my IE back working normally. 
I did read through the issue #96  log and found some registry fixes for WIN7 but not sure if they will work in Win10. 

Thanks in advance for all assistance. 
IKE

**Comment by IkeWSC** [comment]
WOW a WHOLE day and NOT 1 single Comment or suggestion!!
Unbelievable!!!!

**Comment by patrickhlauke** [comment]
dear Ike. sorry that we don't give lightning support for a non-commercial little tool that we provide completely free of charge...

**Comment by patrickhlauke** [comment]
my suggestion: check that you haven't actually disabled image loading, javascript etc using the toolbar itself (in the IE > Toggle Images , IE > Toggle JavaScript etc menu)
