### ISSUE TITLE
Update to latest CCA

### ISSUE THREAD

**Issue by matatk** [ThePacielloGroup/WebAccessibilityToolbar#60]

**Comment by matatk** [comment]
This will involve merging in https://github.com/jun325/WebAccessibilityToolbar/tree/upstream -- however the changes made to Translation ini on our main branch since that one was created will be lost, as we can't yet diff changes to that file.  Those changes will need to be recreated, and appear to be...

 * This one from @menovak: https://github.com/ThePacielloGroup/WebAccessibilityToolbar/commit/9b73a91ccb865bbfb307558ed47a353b7af35d4d#diff-8640d9155f1416df6caf4e88f62db9c4
 * Bump version number from me in my most recent PR.

I should be able to reconstruct them by using diff tools on my local machine which can be coaxed into talking UTF-16.

**Notes:**

* [Change log for Translation.ini in this repo](https://github.com/ThePacielloGroup/WebAccessibilityToolbar/commits/master/wat/Translation.ini)
* [History from Jun's 'upstream' branch](https://github.com/jun325/WebAccessibilityToolbar/commits/c25c5d922d03382087ae913a797b2505ace185a5/wat/Translation.ini)

**Comment by menovak** [comment]
do I need to do something per this email?

**Comment by matatk** [comment]
@menovak: no -- except that, because of the current bottleneck on `Translation.ini` we will not be able to do any further work on WAT until I've merged in the new changes.

**Comment by matatk** [comment]
This is a duplicate of #56 (whoops) -- but let's use this as the official one, because it's got more information in it.

**Comment by matatk** [comment]
I'm sure I've typed this into a textbox somewhere else already this morning, but can't find mention of it anymore: I can no longer access @jun325's branch with these (and other requested) changes on it -- the branch seems to have disappeared from his fork of WAT.

Hopefully it'll be possible to restore it -- at which point I'll merge CCA and the other changes into here.

**Comment by matatk** [comment]
@jun325: just wondering if you could restore the code that is missing, as described above? I can't seem to access it anymore. Thanks!

**Comment by jun325** [comment]
I restored it.

**Comment by matatk** [comment]
@jun325 Thanks for this. I can see that there are two commits you made there:

 * [First commit](https://github.com/jun325/WebAccessibilityToolbar/commit/83e0d62243c7eaa65c2be9b7dfd4718a9366db02)
 * [Second commit](https://github.com/jun325/WebAccessibilityToolbar/commit/c25c5d922d03382087ae913a797b2505ace185a5)

I have a couple of questions...

 1. It seems that there's no x64 DLL there -- please could you include it?
 2. The changes to the DLL were originally made before you updated the DLL to include the change to a UTF-8-encoded Translation.ini.  If I use the DLL from this branch, will we lose those changes?  It seems you may need to produce a new 32- and 64-bit DLL with both sets of changes included?

We are very close to a new stable release based on the code on GitHub; thanks for all of your work on this!

**Comment by jun325** [comment]
I pushed the latest dll. The dll include all changes.

**Comment by matatk** [comment]
I’ve used CCA from https://github.com/jun325/CCA/tree/master/32bit and I have incorporated the changes from the branch at https://github.com/jun325/WebAccessibilityToolbar/tree/upstream .

Largely this is working well (thanks @jun325), but the list of links now opens in a new IE window, rather than a new tab.  Is it possible to swap the window-creating functions in the DLL for tab-creating ones?  Or should we go back to the previous code if we want to open the results in a new tab?

@jun325: Just wondering what you would recommend we do to make the list of links open in a new tab rather than a new IE window?  You can see my latest code in the [bitarch-and-mode-functions](https://github.com/ThePacielloGroup/WebAccessibilityToolbar/tree/bitarch-and-mode-functions) branch — I’ve not made a PR to merge it into WAT/master yet because of this one last issue.

**Comment by jun325** [comment]
hmm...I think about it for a while. The protected mode and popup blocker are troublesome :-(

**Comment by matatk** [comment]
@jun325 thanks -- if there's anything you can do at DLL-level, let us know when you're able.

I think we all agreed that we would just document that the popup blocker needs to be off, for now (which was done, as per #34).  So perhaps simply changing the code for `list_links.ws` back to what it was before would 'fix' this issue for now?  I am wondering if @menovak and @stevefaulkner agree on that -- if so, then we can at address this (as best we can) for now, at least?

**Comment by stevefaulkner** [comment]
@matatk +1 to revert

**Comment by matatk** [comment]
Not sure how I missed this before, but the previous version also opened a new window. However, there is an important advantage to the older behaviour: the window opened *on top* of the existing window.  With the latest changes to the DLL to provide window-opening functions, those windows open *behind* the existing IE window, which is confusing.

So I will revert, but we should also file an extra bug to track @jun325's progress on this and the above issue (of opening tabs instead of windows, at least by default).

**Comment by jun325** [comment]
I uploaded the test version.
https://github.com/ThePacielloGroup/WebAccessibilityToolbar/commit/77c293a1485e55bb7b2d5f8abd4810167cd3af14

**Comment by matatk** [comment]
@jun325: thanks for this.  We are all so busy preparing for CSUN at the moment, but this work is appreciated, thanks!

I'm not sure I understand how we should use `CreateWnd()`, though... you mentioned setting some attributes in the XML, though I thought that the `CreateWnd()` function was being called from [the previous version of `link_list.ws`](https://github.com/ThePacielloGroup/WebAccessibilityToolbar/blob/b7ca449263b1118078c852769a3a4f75244250ca/wat/scripts/link_list.ws).

I gather it will work like this; please let me know if this is right...

 * If we want to cal this from the XML, we would change `<item resid="Validate_HTML_New_M" image="-1" window="new" />` to `<item resid="Validate_HTML_New_M" image="-1" window="tab" />` (though these 'new windows' already open in new tabs -- is that down to the "IE Setting" you mentioned?  Where exactly is that setting?

 * If we want to call `CreateWnd()` from a script, do we have to pass in an argument to make it open in a tab instead of a window?

**Comment by jun325** [comment]
>  * If we want to cal this from the XML, we would change `<item resid="Validate_HTML_New_M" image="-1" window="new" />` to `<item resid="Validate_HTML_New_M" image="-1" window="tab" />` (though these 'new windows' already open in new tabs -- is that down to the "IE Setting" you mentioned?  Where exactly is that setting?

Please see the page below.
http://docs.telerik.com/teststudio/getting-started/configure-your-browser/internet-explorer#pop-ups-open-in-a-new-window
if you change this setting, a new window opens.

>  * If we want to call `CreateWnd()` from a script, do we have to pass in an argument to make it open in a tab instead of a window?

There is no argument. WAT reads a set value of "When a pop-up is encountered" from the registry.
Always open pop-ups in a new window: opens a new window
other set values: opens a new tab
