### ISSUE TITLE
Translation.ini needs to be UTF-8

### ISSUE THREAD

**Issue by matatk** [ThePacielloGroup/WebAccessibilityToolbar#62]
There is a warning on Translation.ini that it must be saved as UTF-16 LE.  However, git needs it to be UTF-8 in order to be able to diff the file.  There is a warning on the Translation.ini file that states it must be saved in UTF-16 LE, however @stevefaulkner and I have tried a small test to see if it works when saved as UTF-8, and it does appear to work OK.

The changes are in a particular branch for now and there is [a test commit to show the diffing working on GitHub](https://github.com/ThePacielloGroup/WebAccessibilityToolbar/commit/2d4b7d72fcb3ea3f47c5540e61605ba3ce35b1bf).

Notes:
 * Marked as a bug as it stops us from developing independently.
 * There are other solutions to this problem, but they involve doing things on the client side, which means we wouldn't be able to see the diffs on GitHub still.

**Comment by matatk** [comment]
Aha, I found some issues.  As well as the attached images, the Dev button doesn't work anymore.

![wat-menu-error1](https://cloud.githubusercontent.com/assets/1125522/5726578/5a0a3c66-9b54-11e4-802f-0270400c1a24.png)
![wat-menu-error2](https://cloud.githubusercontent.com/assets/1125522/5726579/5a32136c-9b54-11e4-90a0-843b774137f5.png)
![wat-menu-error3](https://cloud.githubusercontent.com/assets/1125522/5726580/5a402380-9b54-11e4-816e-79106ffe5f78.png)
![wat-menu-error4](https://cloud.githubusercontent.com/assets/1125522/5726581/5a401b10-9b54-11e4-85b7-6c42ad005d5a.png)

**Comment by jun325** [comment]
I changed the encoding.

**Comment by matatk** [comment]
This is a big relief, it'll make development much easier; thanks @jun325.
