### ISSUE TITLE
New release needs some release notes

### ISSUE THREAD

**Issue by SteveALee** [ThePacielloGroup/WebAccessibilityToolbar#74]
or did you just move to github and make no changes?

**Comment by matatk** [comment]
Good point. We've made a huge number of changes; I'll go back through the commit logs and pick out the highlights.

**Comment by SteveALee** [comment]
Great! Looking forward to seeing what's new and you just reminded me to pass on to someone asking about tools

**Comment by matatk** [comment]
I've added some actual release notes now :-). If you're happy with what's there, please feel free to close this. Thanks again for pointing this one out.

We still have a lot to work on -- as the Issues page shows -- but this is vastly improved over the previous release from our website, and has been stable in daily use, so we felt it was time to go ahead with it.

**Comment by SteveALee** [comment]
Great work, especially like Tenon link. Will give it a spin soon but for now happy to close

**Comment by mpaciello** [comment]
Great stuff Matthew! Well done team!!

 

-Mike

 

Mike Paciello

Email:  <mailto:mpaciello@paciellogroup.com> mpaciello@paciellogroup.com

C: 603.566.7713
