### ISSUE TITLE
Colour>Greyscale not working in IE11

### ISSUE THREAD

**Issue by getterdone** [ThePacielloGroup/WebAccessibilityToolbar#76]
not able to check for colorblindness disability due to greyscale feature not working in IE11.

**Comment by getterdone** [comment]
•Web Accessibility Toolbar 2012 using Windows 7 64-bit IE 11.0.15

**Comment by patrickhlauke** [comment]
WAT 2012 is now outdated. Please uninstall that version and install the latest release (which, among other things, removes the greyscale option, as it relied on IE-specific CSS filters that have been removed in recent versions of IE). https://github.com/ThePacielloGroup/WebAccessibilityToolbar/releases/latest

**Comment by austinstudio** [comment]
Is there any recommended tool to check for grayscale or other types of color blindness since this toolbar won't do it anymore?  My client needs to be able to do it on a local app and can't just paste a URL into another website to have it checked online.

Thanks in advance.
