### ISSUE TITLE
I'm getting constant crashes

### ISSUE THREAD

**Issue by DavidMacDonald** [ThePacielloGroup/WebAccessibilityToolbar#84]
I'm wondering if it is colliding with Zoomtext 10.1 which is not running simultaneously but was installed on the the machine. It seems that problems happened after that install.

I've tried running aViewer from the browser IE WAT toolbar and as a stand alone. They both open. I select the watch focus, and watch mouse... and the red highlight. As soon as I put focus into IE 11 it crashes.

**Comment by menovak** [comment]
hi David

Can you let us know what version of windows, version of WAT, and whether 32 or 64 bit please?

Note, I am using Windows 7 (32 bit) with WAT, and aViewer works fine with IE 11.  ZoomText 10 is installed but not running.  However, if I enable ZoomText, Windows seems to stop so it may well be an issue between ZoomText and aViewer.

Thanks

Mark

**Comment by patrickhlauke** [comment]
Closing, as WAT is no longer in active development.
