### ISSUE TITLE
Functional Accessibility Evaluator issue - WAT2012 / IE11

### ISSUE THREAD

**Issue by RensterUK** [ThePacielloGroup/WebAccessibilityToolbar#94]
Hi All,

If I navigate to any URL, and Select "Check -> Functional Accessibility Evaluator" I get:

![image](https://cloud.githubusercontent.com/assets/12761454/8006504/8038e808-0b8c-11e5-875b-f2e856c792f5.png)

However, if I browser to the FAE site (http://fae.cita.uiuc.edu) and enter the URL there - it works fine.

But I really need to be able to access it via the WAT. Can you please advise?

**Comment by menovak** [comment]
hi RensterUK,

I believe that link was broken in older versions of WAT.  Please download a newer version of WAT from the TPG web site (http://www.paciellogroup.com/resources/wat/) or directly via Github, (https://github.com/ThePacielloGroup/WebAccessibilityToolbar/releases/tag/2015-05-20), and try this again.  I'm running a more recent version of WAT, and the FAE feature operates as expected.

Regards,

Mark

**Comment by patrickhlauke** [comment]
It seems that FAE has been changed recently and doesn't accept POST evaluation requests. using the FAE option in WAT now opens just the FAE homepage, which then requires user to enter/paste the url they want to test. Being pragmatic, I'm closing this, as the original issue itself (the Forbidden message) seems resolved in current WAT
