### ISSUE TITLE
Not able to run FAE in WAT tool(latest version)

### ISSUE THREAD

**Issue by kalleshNS** [ThePacielloGroup/WebAccessibilityToolbar#95]
Hi Team,

I have installed WAT tool from the link : https://github.com/ThePacielloGroup/WebAccessibilityToolbar/releases/tag/2015-05-20
 and trying to run FAE on same but i am not able to get the report for.
I am specifying the url as http://192.168.1.254/cgi-bin/home.ha and clicl on evaluate button, tool says Report processing but not generating any report for long time.

Please provide me the exact steps to run FAE in WAT tool.

Thanks,
Kallesh

**Comment by patrickhlauke** [comment]
FAE is a web-based tool http://fae20.cita.illinois.edu ... so it won't be able to run on non-public sites like ones you just run within your home network.
